package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AdminRole generated by hbm2java
 */
@Entity
@Table(name = "admin_role", catalog = "lovefashion")
public class AdminRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer roleId;
	private AdminUser adminUser;
	private int parentId;
	private short treeLevel;
	private short sortOrder;
	private String roleName;
	private Set<AdminRule> adminRules = new HashSet<AdminRule>(0);

	public AdminRole() {
	}

	public AdminRole(AdminUser adminUser, int parentId, short treeLevel, short sortOrder) {
		this.adminUser = adminUser;
		this.parentId = parentId;
		this.treeLevel = treeLevel;
		this.sortOrder = sortOrder;
	}

	public AdminRole(AdminUser adminUser, int parentId, short treeLevel, short sortOrder, String roleName,
			Set<AdminRule> adminRules) {
		this.adminUser = adminUser;
		this.parentId = parentId;
		this.treeLevel = treeLevel;
		this.sortOrder = sortOrder;
		this.roleName = roleName;
		this.adminRules = adminRules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "role_id", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public AdminUser getAdminUser() {
		return this.adminUser;
	}

	public void setAdminUser(AdminUser adminUser) {
		this.adminUser = adminUser;
	}

	@Column(name = "parent_id", nullable = false)
	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	@Column(name = "tree_level", nullable = false)
	public short getTreeLevel() {
		return this.treeLevel;
	}

	public void setTreeLevel(short treeLevel) {
		this.treeLevel = treeLevel;
	}

	@Column(name = "sort_order", nullable = false)
	public short getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(short sortOrder) {
		this.sortOrder = sortOrder;
	}

	@Column(name = "role_name", length = 50)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adminRole")
	public Set<AdminRule> getAdminRules() {
		return this.adminRules;
	}

	public void setAdminRules(Set<AdminRule> adminRules) {
		this.adminRules = adminRules;
	}

}
