package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatalogCategoryProductId generated by hbm2java
 */
@Embeddable
public class CatalogCategoryProductId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int categoryId;
	private int productId;

	public CatalogCategoryProductId() {
	}

	public CatalogCategoryProductId(int categoryId, int productId) {
		this.categoryId = categoryId;
		this.productId = productId;
	}

	@Column(name = "category_id", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatalogCategoryProductId))
			return false;
		CatalogCategoryProductId castOther = (CatalogCategoryProductId) other;

		return (this.getCategoryId() == castOther.getCategoryId()) && (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCategoryId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
