package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CataloginventoryStock generated by hbm2java
 */
@Entity
@Table(name = "cataloginventory_stock", catalog = "lovefashion")
public class CataloginventoryStock implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Short stockId;
	private String stockName;
	private Set<CataloginventoryStockItem> cataloginventoryStockItems = new HashSet<CataloginventoryStockItem>(0);
	private Set<CataloginventoryStockStatus> cataloginventoryStockStatuses = new HashSet<CataloginventoryStockStatus>(
			0);

	public CataloginventoryStock() {
	}

	public CataloginventoryStock(String stockName, Set<CataloginventoryStockItem> cataloginventoryStockItems,
			Set<CataloginventoryStockStatus> cataloginventoryStockStatuses) {
		this.stockName = stockName;
		this.cataloginventoryStockItems = cataloginventoryStockItems;
		this.cataloginventoryStockStatuses = cataloginventoryStockStatuses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "stock_id", unique = true, nullable = false)
	public Short getStockId() {
		return this.stockId;
	}

	public void setStockId(Short stockId) {
		this.stockId = stockId;
	}

	@Column(name = "stock_name")
	public String getStockName() {
		return this.stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cataloginventoryStock")
	public Set<CataloginventoryStockItem> getCataloginventoryStockItems() {
		return this.cataloginventoryStockItems;
	}

	public void setCataloginventoryStockItems(Set<CataloginventoryStockItem> cataloginventoryStockItems) {
		this.cataloginventoryStockItems = cataloginventoryStockItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cataloginventoryStock")
	public Set<CataloginventoryStockStatus> getCataloginventoryStockStatuses() {
		return this.cataloginventoryStockStatuses;
	}

	public void setCataloginventoryStockStatuses(Set<CataloginventoryStockStatus> cataloginventoryStockStatuses) {
		this.cataloginventoryStockStatuses = cataloginventoryStockStatuses;
	}

}
