package com.example.entity;
// Generated Dec 23, 2015 9:57:00 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CatalogProductEntityGallery generated by hbm2java
 */
@Entity
@Table(name = "catalog_product_entity_gallery", catalog = "lovefashion", uniqueConstraints = @UniqueConstraint(columnNames = "entity_id") )
public class CatalogProductEntityGallery implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer valueId;
	private CatalogProductEntity catalogProductEntity;
	private int position;
	private Integer base;
	private String value;
	private Integer width;
	private Integer height;

	public CatalogProductEntityGallery() {
	}

	public CatalogProductEntityGallery(CatalogProductEntity catalogProductEntity, int position, String value) {
		this.catalogProductEntity = catalogProductEntity;
		this.position = position;
		this.value = value;
	}

	public CatalogProductEntityGallery(CatalogProductEntity catalogProductEntity, int position, Integer base,
			String value, Integer width, Integer height) {
		this.catalogProductEntity = catalogProductEntity;
		this.position = position;
		this.base = base;
		this.value = value;
		this.width = width;
		this.height = height;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "value_id", unique = true, nullable = false)
	public Integer getValueId() {
		return this.valueId;
	}

	public void setValueId(Integer valueId) {
		this.valueId = valueId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entity_id", unique = true, nullable = false)
	public CatalogProductEntity getCatalogProductEntity() {
		return this.catalogProductEntity;
	}

	public void setCatalogProductEntity(CatalogProductEntity catalogProductEntity) {
		this.catalogProductEntity = catalogProductEntity;
	}

	@Column(name = "position", nullable = false)
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	@Column(name = "base")
	public Integer getBase() {
		return this.base;
	}

	public void setBase(Integer base) {
		this.base = base;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "width")
	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	@Column(name = "height")
	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

}
