package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CustomerGroup generated by hbm2java
 */
@Entity
@Table(name = "customer_group", catalog = "lovefashion")
public class CustomerGroup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Short customerGroupId;
	private String customerGroupCode;
	private Integer limitScore;
	private Set<Salesrule> salesrules = new HashSet<Salesrule>(0);
	private Set<CustomerEntity> customerEntities = new HashSet<CustomerEntity>(0);

	public CustomerGroup() {
	}

	public CustomerGroup(String customerGroupCode) {
		this.customerGroupCode = customerGroupCode;
	}
	
	public CustomerGroup(Short customerGroupId) {
		this.customerGroupId = customerGroupId;
	}

	public CustomerGroup(String customerGroupCode, Integer limitScore, Set<Salesrule> salesrules,
			Set<CustomerEntity> customerEntities) {
		this.customerGroupCode = customerGroupCode;
		this.limitScore = limitScore;
		this.salesrules = salesrules;
		this.customerEntities = customerEntities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "customer_group_id", unique = true, nullable = false)
	public Short getCustomerGroupId() {
		return this.customerGroupId;
	}

	public void setCustomerGroupId(Short customerGroupId) {
		this.customerGroupId = customerGroupId;
	}

	@Column(name = "customer_group_code", nullable = false, length = 32)
	public String getCustomerGroupCode() {
		return this.customerGroupCode;
	}

	public void setCustomerGroupCode(String customerGroupCode) {
		this.customerGroupCode = customerGroupCode;
	}

	@Column(name = "limit_score")
	public Integer getLimitScore() {
		return this.limitScore;
	}

	public void setLimitScore(Integer limitScore) {
		this.limitScore = limitScore;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "customerGroups")
	public Set<Salesrule> getSalesrules() {
		return this.salesrules;
	}

	public void setSalesrules(Set<Salesrule> salesrules) {
		this.salesrules = salesrules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerGroup")
	public Set<CustomerEntity> getCustomerEntities() {
		return this.customerEntities;
	}

	public void setCustomerEntities(Set<CustomerEntity> customerEntities) {
		this.customerEntities = customerEntities;
	}

}
