package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EavAttributeOptionValue generated by hbm2java
 */
@Entity
@Table(name = "eav_attribute_option_value", catalog = "lovefashion")
public class EavAttributeOptionValue implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer valueId;
	private EavAttributeOption eavAttributeOption;
	private String value;

	public EavAttributeOptionValue() {
	}

	public EavAttributeOptionValue(EavAttributeOption eavAttributeOption) {
		this.eavAttributeOption = eavAttributeOption;
	}

	public EavAttributeOptionValue(EavAttributeOption eavAttributeOption, String value) {
		this.eavAttributeOption = eavAttributeOption;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "value_id", unique = true, nullable = false)
	public Integer getValueId() {
		return this.valueId;
	}

	public void setValueId(Integer valueId) {
		this.valueId = valueId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "option_id", nullable = false)
	public EavAttributeOption getEavAttributeOption() {
		return this.eavAttributeOption;
	}

	public void setEavAttributeOption(EavAttributeOption eavAttributeOption) {
		this.eavAttributeOption = eavAttributeOption;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
