package com.example.entity;
// Generated Dec 23, 2015 9:57:00 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EavAttribute generated by hbm2java
 */
@Entity
@Table(name = "eav_attribute", catalog = "lovefashion", uniqueConstraints = @UniqueConstraint(columnNames = {
		"entity_type_id", "attribute_code" }) )
public class EavAttribute implements java.io.Serializable {

	private Short attributeId;
	private EavEntityType eavEntityType;
	private String attributeCode;
	private String backendType;
	private String frontendInput;
	private String frontendLabel;
	private short isRequired;
	private String defaultValue;
	private short isUnique;
	private String note;
	private Set<EavAttributeOption> eavAttributeOptions = new HashSet<EavAttributeOption>(0);

	public EavAttribute() {
	}

	public EavAttribute(EavEntityType eavEntityType, String backendType, short isRequired, short isUnique) {
		this.eavEntityType = eavEntityType;
		this.backendType = backendType;
		this.isRequired = isRequired;
		this.isUnique = isUnique;
	}

	public EavAttribute(EavEntityType eavEntityType, String attributeCode, String backendType, String frontendInput,
			String frontendLabel, short isRequired, String defaultValue, short isUnique, String note,
			Set<EavAttributeOption> eavAttributeOptions) {
		this.eavEntityType = eavEntityType;
		this.attributeCode = attributeCode;
		this.backendType = backendType;
		this.frontendInput = frontendInput;
		this.frontendLabel = frontendLabel;
		this.isRequired = isRequired;
		this.defaultValue = defaultValue;
		this.isUnique = isUnique;
		this.note = note;
		this.eavAttributeOptions = eavAttributeOptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "attribute_id", unique = true, nullable = false)
	public Short getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(Short attributeId) {
		this.attributeId = attributeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entity_type_id", nullable = false)
	public EavEntityType getEavEntityType() {
		return this.eavEntityType;
	}

	public void setEavEntityType(EavEntityType eavEntityType) {
		this.eavEntityType = eavEntityType;
	}

	@Column(name = "attribute_code")
	public String getAttributeCode() {
		return this.attributeCode;
	}

	public void setAttributeCode(String attributeCode) {
		this.attributeCode = attributeCode;
	}

	@Column(name = "backend_type", nullable = false, length = 8)
	public String getBackendType() {
		return this.backendType;
	}

	public void setBackendType(String backendType) {
		this.backendType = backendType;
	}

	@Column(name = "frontend_input", length = 50)
	public String getFrontendInput() {
		return this.frontendInput;
	}

	public void setFrontendInput(String frontendInput) {
		this.frontendInput = frontendInput;
	}

	@Column(name = "frontend_label")
	public String getFrontendLabel() {
		return this.frontendLabel;
	}

	public void setFrontendLabel(String frontendLabel) {
		this.frontendLabel = frontendLabel;
	}

	@Column(name = "is_required", nullable = false)
	public short getIsRequired() {
		return this.isRequired;
	}

	public void setIsRequired(short isRequired) {
		this.isRequired = isRequired;
	}

	@Column(name = "default_value", length = 65535)
	public String getDefaultValue() {
		return this.defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	@Column(name = "is_unique", nullable = false)
	public short getIsUnique() {
		return this.isUnique;
	}

	public void setIsUnique(short isUnique) {
		this.isUnique = isUnique;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eavAttribute")
	public Set<EavAttributeOption> getEavAttributeOptions() {
		return this.eavAttributeOptions;
	}

	public void setEavAttributeOptions(Set<EavAttributeOption> eavAttributeOptions) {
		this.eavAttributeOptions = eavAttributeOptions;
	}

}
