package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EavEntityType generated by hbm2java
 */
@Entity
@Table(name = "eav_entity_type", catalog = "lovefashion")
public class EavEntityType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Short entityTypeId;
	private String entityTypeCode;
	private String entityModel;
	private String attributeModel;
	private String entityTable;
	private Set<EavAttribute> eavAttributes = new HashSet<EavAttribute>(0);

	public EavEntityType() {
	}

	public EavEntityType(String entityTypeCode, String entityModel) {
		this.entityTypeCode = entityTypeCode;
		this.entityModel = entityModel;
	}

	public EavEntityType(String entityTypeCode, String entityModel, String attributeModel, String entityTable,
			Set<EavAttribute> eavAttributes) {
		this.entityTypeCode = entityTypeCode;
		this.entityModel = entityModel;
		this.attributeModel = attributeModel;
		this.entityTable = entityTable;
		this.eavAttributes = eavAttributes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "entity_type_id", unique = true, nullable = false)
	public Short getEntityTypeId() {
		return this.entityTypeId;
	}

	public void setEntityTypeId(Short entityTypeId) {
		this.entityTypeId = entityTypeId;
	}

	@Column(name = "entity_type_code", nullable = false, length = 50)
	public String getEntityTypeCode() {
		return this.entityTypeCode;
	}

	public void setEntityTypeCode(String entityTypeCode) {
		this.entityTypeCode = entityTypeCode;
	}

	@Column(name = "entity_model", nullable = false)
	public String getEntityModel() {
		return this.entityModel;
	}

	public void setEntityModel(String entityModel) {
		this.entityModel = entityModel;
	}

	@Column(name = "attribute_model")
	public String getAttributeModel() {
		return this.attributeModel;
	}

	public void setAttributeModel(String attributeModel) {
		this.attributeModel = attributeModel;
	}

	@Column(name = "entity_table")
	public String getEntityTable() {
		return this.entityTable;
	}

	public void setEntityTable(String entityTable) {
		this.entityTable = entityTable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eavEntityType")
	public Set<EavAttribute> getEavAttributes() {
		return this.eavAttributes;
	}

	public void setEavAttributes(Set<EavAttribute> eavAttributes) {
		this.eavAttributes = eavAttributes;
	}

}
