package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * EmailTemplate generated by hbm2java
 */
@Entity
@Table(name = "email_template", catalog = "lovefashion", uniqueConstraints = @UniqueConstraint(columnNames = "template_code") )
public class EmailTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer templateId;
	private String templateCode;
	private String templateText;
	private int templateType;
	private String templateSubject;
	private String templateSenderName;
	private String templateSenderEmail;
	private Date addAt;

	public EmailTemplate() {
	}

	public EmailTemplate(String templateCode, String templateText, int templateType, String templateSubject,
			String templateSenderName, String templateSenderEmail, Date addAt) {
		this.templateCode = templateCode;
		this.templateText = templateText;
		this.templateType = templateType;
		this.templateSubject = templateSubject;
		this.templateSenderName = templateSenderName;
		this.templateSenderEmail = templateSenderEmail;
		this.addAt = addAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "template_id", unique = true, nullable = false)
	public Integer getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(Integer templateId) {
		this.templateId = templateId;
	}

	@Column(name = "template_code", unique = true, nullable = false, length = 150)
	public String getTemplateCode() {
		return this.templateCode;
	}

	public void setTemplateCode(String templateCode) {
		this.templateCode = templateCode;
	}

	@Column(name = "template_text", nullable = false, length = 65535)
	public String getTemplateText() {
		return this.templateText;
	}

	public void setTemplateText(String templateText) {
		this.templateText = templateText;
	}

	@Column(name = "template_type", nullable = false)
	public int getTemplateType() {
		return this.templateType;
	}

	public void setTemplateType(int templateType) {
		this.templateType = templateType;
	}

	@Column(name = "template_subject", nullable = false, length = 200)
	public String getTemplateSubject() {
		return this.templateSubject;
	}

	public void setTemplateSubject(String templateSubject) {
		this.templateSubject = templateSubject;
	}

	@Column(name = "template_sender_name", nullable = false, length = 200)
	public String getTemplateSenderName() {
		return this.templateSenderName;
	}

	public void setTemplateSenderName(String templateSenderName) {
		this.templateSenderName = templateSenderName;
	}

	@Column(name = "template_sender_email", nullable = false, length = 200)
	public String getTemplateSenderEmail() {
		return this.templateSenderEmail;
	}

	public void setTemplateSenderEmail(String templateSenderEmail) {
		this.templateSenderEmail = templateSenderEmail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_at", nullable = false, length = 19)
	public Date getAddAt() {
		return this.addAt;
	}

	public void setAddAt(Date addAt) {
		this.addAt = addAt;
	}

}
