package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogCustomer generated by hbm2java
 */
@Entity
@Table(name = "log_customer", catalog = "lovefashion")
public class LogCustomer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer logId;
	private int customerId;
	private Date loginAt;
	private Date logoutAt;

	public LogCustomer() {
	}

	public LogCustomer(int customerId, Date loginAt) {
		this.customerId = customerId;
		this.loginAt = loginAt;
	}

	public LogCustomer(int customerId, Date loginAt, Date logoutAt) {
		this.customerId = customerId;
		this.loginAt = loginAt;
		this.logoutAt = logoutAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "log_id", unique = true, nullable = false)
	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	@Column(name = "customer_id", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "login_at", nullable = false, length = 19)
	public Date getLoginAt() {
		return this.loginAt;
	}

	public void setLoginAt(Date loginAt) {
		this.loginAt = loginAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logout_at", length = 19)
	public Date getLogoutAt() {
		return this.logoutAt;
	}

	public void setLogoutAt(Date logoutAt) {
		this.logoutAt = logoutAt;
	}

}
