package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SalesOrderPayment generated by hbm2java
 */
@Entity
@Table(name = "sales_order_payment", catalog = "lovefashion")
public class SalesOrderPayment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer entityId;
	private SalesOrder salesOrder;
	private BigDecimal amountCanceled;
	private BigDecimal amountPaid;
	private double amountOrdered;
	private BigDecimal shippingAmount;
	private BigDecimal baseAmountPaidOnline;
	private BigDecimal baseAmountRefundedOnline;
	private BigDecimal shippingRefunded;
	private String ccExpMonth;
	private String ccSsStartYear;
	private String echeckBankName;
	private String method;
	private Set<SalesPaymentTransaction> salesPaymentTransactions = new HashSet<SalesPaymentTransaction>(0);

	public SalesOrderPayment() {
	}

	public SalesOrderPayment(SalesOrder salesOrder) {
		this.salesOrder = salesOrder;
	}

	public SalesOrderPayment(SalesOrder salesOrder, BigDecimal amountCanceled, BigDecimal amountPaid,
			double amountOrdered, BigDecimal shippingAmount, BigDecimal baseAmountPaidOnline,
			BigDecimal baseAmountRefundedOnline, BigDecimal shippingRefunded, String ccExpMonth, String ccSsStartYear,
			String echeckBankName, String method, Set<SalesPaymentTransaction> salesPaymentTransactions) {
		this.salesOrder = salesOrder;
		this.amountCanceled = amountCanceled;
		this.amountPaid = amountPaid;
		this.amountOrdered = amountOrdered;
		this.shippingAmount = shippingAmount;
		this.baseAmountPaidOnline = baseAmountPaidOnline;
		this.baseAmountRefundedOnline = baseAmountRefundedOnline;
		this.shippingRefunded = shippingRefunded;
		this.ccExpMonth = ccExpMonth;
		this.ccSsStartYear = ccSsStartYear;
		this.echeckBankName = echeckBankName;
		this.method = method;
		this.salesPaymentTransactions = salesPaymentTransactions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "entity_id", unique = true, nullable = false)
	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id", nullable = false)
	public SalesOrder getSalesOrder() {
		return this.salesOrder;
	}

	public void setSalesOrder(SalesOrder salesOrder) {
		this.salesOrder = salesOrder;
	}

	@Column(name = "amount_canceled", precision = 12, scale = 4)
	public BigDecimal getAmountCanceled() {
		return this.amountCanceled;
	}

	public void setAmountCanceled(BigDecimal amountCanceled) {
		this.amountCanceled = amountCanceled;
	}

	@Column(name = "amount_paid", precision = 12, scale = 4)
	public BigDecimal getAmountPaid() {
		return this.amountPaid;
	}

	public void setAmountPaid(BigDecimal amountPaid) {
		this.amountPaid = amountPaid;
	}

	@Column(name = "amount_ordered", precision = 12, scale = 4)
	public double getAmountOrdered() {
		return this.amountOrdered;
	}

	public void setAmountOrdered(double amountOrdered) {
		this.amountOrdered = amountOrdered;
	}

	@Column(name = "shipping_amount", precision = 12, scale = 4)
	public BigDecimal getShippingAmount() {
		return this.shippingAmount;
	}

	public void setShippingAmount(BigDecimal shippingAmount) {
		this.shippingAmount = shippingAmount;
	}

	@Column(name = "base_amount_paid_online", precision = 12, scale = 4)
	public BigDecimal getBaseAmountPaidOnline() {
		return this.baseAmountPaidOnline;
	}

	public void setBaseAmountPaidOnline(BigDecimal baseAmountPaidOnline) {
		this.baseAmountPaidOnline = baseAmountPaidOnline;
	}

	@Column(name = "base_amount_refunded_online", precision = 12, scale = 4)
	public BigDecimal getBaseAmountRefundedOnline() {
		return this.baseAmountRefundedOnline;
	}

	public void setBaseAmountRefundedOnline(BigDecimal baseAmountRefundedOnline) {
		this.baseAmountRefundedOnline = baseAmountRefundedOnline;
	}

	@Column(name = "shipping_refunded", precision = 12, scale = 4)
	public BigDecimal getShippingRefunded() {
		return this.shippingRefunded;
	}

	public void setShippingRefunded(BigDecimal shippingRefunded) {
		this.shippingRefunded = shippingRefunded;
	}

	@Column(name = "cc_exp_month")
	public String getCcExpMonth() {
		return this.ccExpMonth;
	}

	public void setCcExpMonth(String ccExpMonth) {
		this.ccExpMonth = ccExpMonth;
	}

	@Column(name = "cc_ss_start_year")
	public String getCcSsStartYear() {
		return this.ccSsStartYear;
	}

	public void setCcSsStartYear(String ccSsStartYear) {
		this.ccSsStartYear = ccSsStartYear;
	}

	@Column(name = "echeck_bank_name")
	public String getEcheckBankName() {
		return this.echeckBankName;
	}

	public void setEcheckBankName(String echeckBankName) {
		this.echeckBankName = echeckBankName;
	}

	@Column(name = "method")
	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesOrderPayment")
	public Set<SalesPaymentTransaction> getSalesPaymentTransactions() {
		return this.salesPaymentTransactions;
	}

	public void setSalesPaymentTransactions(Set<SalesPaymentTransaction> salesPaymentTransactions) {
		this.salesPaymentTransactions = salesPaymentTransactions;
	}

}
