package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SalesCreditmemoItem generated by hbm2java
 */
@Entity
@Table(name = "sales_creditmemo_item", catalog = "lovefashion")
public class SalesCreditmemoItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer entityId;
	private SalesCreditmemo salesCreditmemo;
	private BigDecimal basePrice;
	private BigDecimal taxAmount;
	private BigDecimal discountAmount;
	private BigDecimal rowTotal;
	private BigDecimal priceInclTax;
	private BigDecimal qty;
	private BigDecimal price;
	private BigDecimal rowTotalInclTax;
	private Integer productId;
	private Integer orderItemId;
	private String sku;
	private String name;

	public SalesCreditmemoItem() {
	}

	public SalesCreditmemoItem(SalesCreditmemo salesCreditmemo) {
		this.salesCreditmemo = salesCreditmemo;
	}

	public SalesCreditmemoItem(SalesCreditmemo salesCreditmemo, BigDecimal basePrice, BigDecimal taxAmount,
			BigDecimal discountAmount, BigDecimal rowTotal, BigDecimal priceInclTax, BigDecimal qty, BigDecimal price,
			BigDecimal rowTotalInclTax, Integer productId, Integer orderItemId, String sku, String name) {
		this.salesCreditmemo = salesCreditmemo;
		this.basePrice = basePrice;
		this.taxAmount = taxAmount;
		this.discountAmount = discountAmount;
		this.rowTotal = rowTotal;
		this.priceInclTax = priceInclTax;
		this.qty = qty;
		this.price = price;
		this.rowTotalInclTax = rowTotalInclTax;
		this.productId = productId;
		this.orderItemId = orderItemId;
		this.sku = sku;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "entity_id", unique = true, nullable = false)
	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id", nullable = false)
	public SalesCreditmemo getSalesCreditmemo() {
		return this.salesCreditmemo;
	}

	public void setSalesCreditmemo(SalesCreditmemo salesCreditmemo) {
		this.salesCreditmemo = salesCreditmemo;
	}

	@Column(name = "base_price", precision = 12, scale = 4)
	public BigDecimal getBasePrice() {
		return this.basePrice;
	}

	public void setBasePrice(BigDecimal basePrice) {
		this.basePrice = basePrice;
	}

	@Column(name = "tax_amount", precision = 12, scale = 4)
	public BigDecimal getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(BigDecimal taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "discount_amount", precision = 12, scale = 4)
	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "row_total", precision = 12, scale = 4)
	public BigDecimal getRowTotal() {
		return this.rowTotal;
	}

	public void setRowTotal(BigDecimal rowTotal) {
		this.rowTotal = rowTotal;
	}

	@Column(name = "price_incl_tax", precision = 12, scale = 4)
	public BigDecimal getPriceInclTax() {
		return this.priceInclTax;
	}

	public void setPriceInclTax(BigDecimal priceInclTax) {
		this.priceInclTax = priceInclTax;
	}

	@Column(name = "qty", precision = 12, scale = 4)
	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Column(name = "price", precision = 12, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "row_total_incl_tax", precision = 12, scale = 4)
	public BigDecimal getRowTotalInclTax() {
		return this.rowTotalInclTax;
	}

	public void setRowTotalInclTax(BigDecimal rowTotalInclTax) {
		this.rowTotalInclTax = rowTotalInclTax;
	}

	@Column(name = "product_id")
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "order_item_id")
	public Integer getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(Integer orderItemId) {
		this.orderItemId = orderItemId;
	}

	@Column(name = "sku")
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
