package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SalesInvoice generated by hbm2java
 */
@Entity
@Table(name = "sales_invoice", catalog = "lovefashion")
public class SalesInvoice implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer entityId;
	private SalesOrder salesOrder;
	private Store store;
	private BigDecimal baseGrandTotal;
	private BigDecimal taxAmount;
	private BigDecimal discountAmount;
	private BigDecimal grandTotal;
	private BigDecimal shippingAmount;
	private BigDecimal subtotalInclTax;
	private BigDecimal totalQty;
	private BigDecimal subtotal;
	private Integer billingAddressId;
	private Integer state;
	private Integer shippingAddressId;
	private Date createdAt;
	private Date updatedAt;
	private Set<SalesInvoiceItem> salesInvoiceItems = new HashSet<SalesInvoiceItem>(0);

	public SalesInvoice() {
	}

	public SalesInvoice(SalesOrder salesOrder) {
		this.salesOrder = salesOrder;
	}

	public SalesInvoice(SalesOrder salesOrder, Store store, BigDecimal baseGrandTotal, BigDecimal taxAmount,
			BigDecimal discountAmount, BigDecimal grandTotal, BigDecimal shippingAmount, BigDecimal subtotalInclTax,
			BigDecimal totalQty, BigDecimal subtotal, Integer billingAddressId, Integer state,
			Integer shippingAddressId, Date createdAt, Date updatedAt, Set<SalesInvoiceItem> salesInvoiceItems) {
		this.salesOrder = salesOrder;
		this.store = store;
		this.baseGrandTotal = baseGrandTotal;
		this.taxAmount = taxAmount;
		this.discountAmount = discountAmount;
		this.grandTotal = grandTotal;
		this.shippingAmount = shippingAmount;
		this.subtotalInclTax = subtotalInclTax;
		this.totalQty = totalQty;
		this.subtotal = subtotal;
		this.billingAddressId = billingAddressId;
		this.state = state;
		this.shippingAddressId = shippingAddressId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.salesInvoiceItems = salesInvoiceItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "entity_id", unique = true, nullable = false)
	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public SalesOrder getSalesOrder() {
		return this.salesOrder;
	}

	public void setSalesOrder(SalesOrder salesOrder) {
		this.salesOrder = salesOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id")
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@Column(name = "base_grand_total", precision = 12, scale = 4)
	public BigDecimal getBaseGrandTotal() {
		return this.baseGrandTotal;
	}

	public void setBaseGrandTotal(BigDecimal baseGrandTotal) {
		this.baseGrandTotal = baseGrandTotal;
	}

	@Column(name = "tax_amount", precision = 12, scale = 4)
	public BigDecimal getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(BigDecimal taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "discount_amount", precision = 12, scale = 4)
	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "grand_total", precision = 12, scale = 4)
	public BigDecimal getGrandTotal() {
		return this.grandTotal;
	}

	public void setGrandTotal(BigDecimal grandTotal) {
		this.grandTotal = grandTotal;
	}

	@Column(name = "shipping_amount", precision = 12, scale = 4)
	public BigDecimal getShippingAmount() {
		return this.shippingAmount;
	}

	public void setShippingAmount(BigDecimal shippingAmount) {
		this.shippingAmount = shippingAmount;
	}

	@Column(name = "subtotal_incl_tax", precision = 12, scale = 4)
	public BigDecimal getSubtotalInclTax() {
		return this.subtotalInclTax;
	}

	public void setSubtotalInclTax(BigDecimal subtotalInclTax) {
		this.subtotalInclTax = subtotalInclTax;
	}

	@Column(name = "total_qty", precision = 12, scale = 4)
	public BigDecimal getTotalQty() {
		return this.totalQty;
	}

	public void setTotalQty(BigDecimal totalQty) {
		this.totalQty = totalQty;
	}

	@Column(name = "subtotal", precision = 12, scale = 4)
	public BigDecimal getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(BigDecimal subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "billing_address_id")
	public Integer getBillingAddressId() {
		return this.billingAddressId;
	}

	public void setBillingAddressId(Integer billingAddressId) {
		this.billingAddressId = billingAddressId;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Column(name = "shipping_address_id")
	public Integer getShippingAddressId() {
		return this.shippingAddressId;
	}

	public void setShippingAddressId(Integer shippingAddressId) {
		this.shippingAddressId = shippingAddressId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesInvoice")
	public Set<SalesInvoiceItem> getSalesInvoiceItems() {
		return this.salesInvoiceItems;
	}

	public void setSalesInvoiceItems(Set<SalesInvoiceItem> salesInvoiceItems) {
		this.salesInvoiceItems = salesInvoiceItems;
	}

}
