package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SalesruleCouponUsage generated by hbm2java
 */
@Entity
@Table(name = "salesrule_coupon_usage", catalog = "lovefashion")
public class SalesruleCouponUsage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private SalesruleCouponUsageId id;
	private CustomerEntity customerEntity;
	private SalesruleCoupon salesruleCoupon;
	private int timesUsed;

	public SalesruleCouponUsage() {
	}

	public SalesruleCouponUsage(SalesruleCouponUsageId id, CustomerEntity customerEntity,
			SalesruleCoupon salesruleCoupon, int timesUsed) {
		this.id = id;
		this.customerEntity = customerEntity;
		this.salesruleCoupon = salesruleCoupon;
		this.timesUsed = timesUsed;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "couponId", column = @Column(name = "coupon_id", nullable = false) ),
			@AttributeOverride(name = "customerId", column = @Column(name = "customer_id", nullable = false) ) })
	public SalesruleCouponUsageId getId() {
		return this.id;
	}

	public void setId(SalesruleCouponUsageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false, insertable = false, updatable = false)
	public CustomerEntity getCustomerEntity() {
		return this.customerEntity;
	}

	public void setCustomerEntity(CustomerEntity customerEntity) {
		this.customerEntity = customerEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_id", nullable = false, insertable = false, updatable = false)
	public SalesruleCoupon getSalesruleCoupon() {
		return this.salesruleCoupon;
	}

	public void setSalesruleCoupon(SalesruleCoupon salesruleCoupon) {
		this.salesruleCoupon = salesruleCoupon;
	}

	@Column(name = "times_used", nullable = false)
	public int getTimesUsed() {
		return this.timesUsed;
	}

	public void setTimesUsed(int timesUsed) {
		this.timesUsed = timesUsed;
	}

}
