package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SalesInvoiceItem generated by hbm2java
 */
@Entity
@Table(name = "sales_invoice_item", catalog = "lovefashion")
public class SalesInvoiceItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer entityId;
	private SalesInvoice salesInvoice;
	private BigDecimal basePrice;
	private BigDecimal taxAmount;
	private BigDecimal baseRowTotal;
	private BigDecimal discountAmount;
	private BigDecimal rowTotal;
	private BigDecimal baseDiscountAmount;
	private BigDecimal priceInclTax;
	private BigDecimal baseTaxAmount;
	private BigDecimal qty;
	private BigDecimal price;
	private BigDecimal rowTotalInclTax;
	private Integer productId;
	private Integer orderItemId;
	private String sku;

	public SalesInvoiceItem() {
	}

	public SalesInvoiceItem(SalesInvoice salesInvoice) {
		this.salesInvoice = salesInvoice;
	}

	public SalesInvoiceItem(SalesInvoice salesInvoice, BigDecimal basePrice, BigDecimal taxAmount,
			BigDecimal baseRowTotal, BigDecimal discountAmount, BigDecimal rowTotal, BigDecimal baseDiscountAmount,
			BigDecimal priceInclTax, BigDecimal baseTaxAmount, BigDecimal qty, BigDecimal price,
			BigDecimal rowTotalInclTax, Integer productId, Integer orderItemId, String sku) {
		this.salesInvoice = salesInvoice;
		this.basePrice = basePrice;
		this.taxAmount = taxAmount;
		this.baseRowTotal = baseRowTotal;
		this.discountAmount = discountAmount;
		this.rowTotal = rowTotal;
		this.baseDiscountAmount = baseDiscountAmount;
		this.priceInclTax = priceInclTax;
		this.baseTaxAmount = baseTaxAmount;
		this.qty = qty;
		this.price = price;
		this.rowTotalInclTax = rowTotalInclTax;
		this.productId = productId;
		this.orderItemId = orderItemId;
		this.sku = sku;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "entity_id", unique = true, nullable = false)
	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id", nullable = false)
	public SalesInvoice getSalesInvoice() {
		return this.salesInvoice;
	}

	public void setSalesInvoice(SalesInvoice salesInvoice) {
		this.salesInvoice = salesInvoice;
	}

	@Column(name = "base_price", precision = 12, scale = 4)
	public BigDecimal getBasePrice() {
		return this.basePrice;
	}

	public void setBasePrice(BigDecimal basePrice) {
		this.basePrice = basePrice;
	}

	@Column(name = "tax_amount", precision = 12, scale = 4)
	public BigDecimal getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(BigDecimal taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "base_row_total", precision = 12, scale = 4)
	public BigDecimal getBaseRowTotal() {
		return this.baseRowTotal;
	}

	public void setBaseRowTotal(BigDecimal baseRowTotal) {
		this.baseRowTotal = baseRowTotal;
	}

	@Column(name = "discount_amount", precision = 12, scale = 4)
	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "row_total", precision = 12, scale = 4)
	public BigDecimal getRowTotal() {
		return this.rowTotal;
	}

	public void setRowTotal(BigDecimal rowTotal) {
		this.rowTotal = rowTotal;
	}

	@Column(name = "base_discount_amount", precision = 12, scale = 4)
	public BigDecimal getBaseDiscountAmount() {
		return this.baseDiscountAmount;
	}

	public void setBaseDiscountAmount(BigDecimal baseDiscountAmount) {
		this.baseDiscountAmount = baseDiscountAmount;
	}

	@Column(name = "price_incl_tax", precision = 12, scale = 4)
	public BigDecimal getPriceInclTax() {
		return this.priceInclTax;
	}

	public void setPriceInclTax(BigDecimal priceInclTax) {
		this.priceInclTax = priceInclTax;
	}

	@Column(name = "base_tax_amount", precision = 12, scale = 4)
	public BigDecimal getBaseTaxAmount() {
		return this.baseTaxAmount;
	}

	public void setBaseTaxAmount(BigDecimal baseTaxAmount) {
		this.baseTaxAmount = baseTaxAmount;
	}

	@Column(name = "qty", precision = 12, scale = 4)
	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Column(name = "price", precision = 12, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "row_total_incl_tax", precision = 12, scale = 4)
	public BigDecimal getRowTotalInclTax() {
		return this.rowTotalInclTax;
	}

	public void setRowTotalInclTax(BigDecimal rowTotalInclTax) {
		this.rowTotalInclTax = rowTotalInclTax;
	}

	@Column(name = "product_id")
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "order_item_id")
	public Integer getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(Integer orderItemId) {
		this.orderItemId = orderItemId;
	}

	@Column(name = "sku")
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

}
