package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SalesruleCouponUsageId generated by hbm2java
 */
@Embeddable
public class SalesruleCouponUsageId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int couponId;
	private int customerId;

	public SalesruleCouponUsageId() {
	}

	public SalesruleCouponUsageId(int couponId, int customerId) {
		this.couponId = couponId;
		this.customerId = customerId;
	}

	@Column(name = "coupon_id", nullable = false)
	public int getCouponId() {
		return this.couponId;
	}

	public void setCouponId(int couponId) {
		this.couponId = couponId;
	}

	@Column(name = "customer_id", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SalesruleCouponUsageId))
			return false;
		SalesruleCouponUsageId castOther = (SalesruleCouponUsageId) other;

		return (this.getCouponId() == castOther.getCouponId()) && (this.getCustomerId() == castOther.getCustomerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCouponId();
		result = 37 * result + this.getCustomerId();
		return result;
	}

}
