package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SalesShipmentItem generated by hbm2java
 */
@Entity
@Table(name = "sales_shipment_item", catalog = "lovefashion")
public class SalesShipmentItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer entityId;
	private SalesShipment salesShipment;
	private BigDecimal rowTotal;
	private BigDecimal price;
	private BigDecimal weight;
	private BigDecimal qty;
	private Integer productId;
	private Integer orderItemId;
	private String name;
	private String sku;

	public SalesShipmentItem() {
	}

	public SalesShipmentItem(SalesShipment salesShipment) {
		this.salesShipment = salesShipment;
	}

	public SalesShipmentItem(SalesShipment salesShipment, BigDecimal rowTotal, BigDecimal price, BigDecimal weight,
			BigDecimal qty, Integer productId, Integer orderItemId, String name, String sku) {
		this.salesShipment = salesShipment;
		this.rowTotal = rowTotal;
		this.price = price;
		this.weight = weight;
		this.qty = qty;
		this.productId = productId;
		this.orderItemId = orderItemId;
		this.name = name;
		this.sku = sku;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "entity_id", unique = true, nullable = false)
	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id", nullable = false)
	public SalesShipment getSalesShipment() {
		return this.salesShipment;
	}

	public void setSalesShipment(SalesShipment salesShipment) {
		this.salesShipment = salesShipment;
	}

	@Column(name = "row_total", precision = 12, scale = 4)
	public BigDecimal getRowTotal() {
		return this.rowTotal;
	}

	public void setRowTotal(BigDecimal rowTotal) {
		this.rowTotal = rowTotal;
	}

	@Column(name = "price", precision = 12, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "weight", precision = 12, scale = 4)
	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	@Column(name = "qty", precision = 12, scale = 4)
	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Column(name = "product_id")
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "order_item_id")
	public Integer getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(Integer orderItemId) {
		this.orderItemId = orderItemId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sku")
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

}
