package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SalesShipment generated by hbm2java
 */
@Entity
@Table(name = "sales_shipment", catalog = "lovefashion")
public class SalesShipment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer entityId;
	private SalesOrder salesOrder;
	private Store store;
	private BigDecimal totalWeight;
	private BigDecimal totalQty;
	private Integer customerId;
	private Integer shippingAddressId;
	private Integer billingAddressId;
	private Integer shipmentStatus;
	private Date createdAt;
	private Date updatedAt;
	private Set<SalesShipmentItem> salesShipmentItems = new HashSet<SalesShipmentItem>(0);

	public SalesShipment() {
	}

	public SalesShipment(SalesOrder salesOrder) {
		this.salesOrder = salesOrder;
	}

	public SalesShipment(SalesOrder salesOrder, Store store, BigDecimal totalWeight, BigDecimal totalQty,
			Integer customerId, Integer shippingAddressId, Integer billingAddressId, Integer shipmentStatus,
			Date createdAt, Date updatedAt, Set<SalesShipmentItem> salesShipmentItems) {
		this.salesOrder = salesOrder;
		this.store = store;
		this.totalWeight = totalWeight;
		this.totalQty = totalQty;
		this.customerId = customerId;
		this.shippingAddressId = shippingAddressId;
		this.billingAddressId = billingAddressId;
		this.shipmentStatus = shipmentStatus;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.salesShipmentItems = salesShipmentItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "entity_id", unique = true, nullable = false)
	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public SalesOrder getSalesOrder() {
		return this.salesOrder;
	}

	public void setSalesOrder(SalesOrder salesOrder) {
		this.salesOrder = salesOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id")
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@Column(name = "total_weight", precision = 12, scale = 4)
	public BigDecimal getTotalWeight() {
		return this.totalWeight;
	}

	public void setTotalWeight(BigDecimal totalWeight) {
		this.totalWeight = totalWeight;
	}

	@Column(name = "total_qty", precision = 12, scale = 4)
	public BigDecimal getTotalQty() {
		return this.totalQty;
	}

	public void setTotalQty(BigDecimal totalQty) {
		this.totalQty = totalQty;
	}

	@Column(name = "customer_id")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "shipping_address_id")
	public Integer getShippingAddressId() {
		return this.shippingAddressId;
	}

	public void setShippingAddressId(Integer shippingAddressId) {
		this.shippingAddressId = shippingAddressId;
	}

	@Column(name = "billing_address_id")
	public Integer getBillingAddressId() {
		return this.billingAddressId;
	}

	public void setBillingAddressId(Integer billingAddressId) {
		this.billingAddressId = billingAddressId;
	}

	@Column(name = "shipment_status")
	public Integer getShipmentStatus() {
		return this.shipmentStatus;
	}

	public void setShipmentStatus(Integer shipmentStatus) {
		this.shipmentStatus = shipmentStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesShipment")
	public Set<SalesShipmentItem> getSalesShipmentItems() {
		return this.salesShipmentItems;
	}

	public void setSalesShipmentItems(Set<SalesShipmentItem> salesShipmentItems) {
		this.salesShipmentItems = salesShipmentItems;
	}

}
