package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SalesruleCustomer generated by hbm2java
 */
@Entity
@Table(name = "salesrule_customer", catalog = "lovefashion")
public class SalesruleCustomer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer ruleCustomerId;
	private CustomerEntity customerEntity;
	private Salesrule salesrule;
	private short timesUsed;

	public SalesruleCustomer() {
	}

	public SalesruleCustomer(CustomerEntity customerEntity, Salesrule salesrule, short timesUsed) {
		this.customerEntity = customerEntity;
		this.salesrule = salesrule;
		this.timesUsed = timesUsed;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rule_customer_id", unique = true, nullable = false)
	public Integer getRuleCustomerId() {
		return this.ruleCustomerId;
	}

	public void setRuleCustomerId(Integer ruleCustomerId) {
		this.ruleCustomerId = ruleCustomerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public CustomerEntity getCustomerEntity() {
		return this.customerEntity;
	}

	public void setCustomerEntity(CustomerEntity customerEntity) {
		this.customerEntity = customerEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rule_id", nullable = false)
	public Salesrule getSalesrule() {
		return this.salesrule;
	}

	public void setSalesrule(Salesrule salesrule) {
		this.salesrule = salesrule;
	}

	@Column(name = "times_used", nullable = false)
	public short getTimesUsed() {
		return this.timesUsed;
	}

	public void setTimesUsed(short timesUsed) {
		this.timesUsed = timesUsed;
	}

}
