package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StoreGroup generated by hbm2java
 */
@Entity
@Table(name = "store_group", catalog = "lovefashion")
public class StoreGroup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Short groupId;
	private String name;
	private Set<Store> stores = new HashSet<Store>(0);

	public StoreGroup() {
	}

	public StoreGroup(String name) {
		this.name = name;
	}

	public StoreGroup(String name, Set<Store> stores) {
		this.name = name;
		this.stores = stores;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "group_id", unique = true, nullable = false)
	public Short getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Short groupId) {
		this.groupId = groupId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storeGroup")
	public Set<Store> getStores() {
		return this.stores;
	}

	public void setStores(Set<Store> stores) {
		this.stores = stores;
	}

}
