package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaxCalculationRate generated by hbm2java
 */
@Entity
@Table(name = "tax_calculation_rate", catalog = "lovefashion")
public class TaxCalculationRate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer taxCalculationRateId;
	private String taxCountryId;
	private int taxRegionId;
	private String code;
	private double rate;
	private Set<TaxCalculation> taxCalculations = new HashSet<TaxCalculation>(0);

	public TaxCalculationRate() {
	}

	public TaxCalculationRate(String taxCountryId, int taxRegionId, String code, double rate) {
		this.taxCountryId = taxCountryId;
		this.taxRegionId = taxRegionId;
		this.code = code;
		this.rate = rate;
	}

	public TaxCalculationRate(String taxCountryId, int taxRegionId, String code, double rate,
			Set<TaxCalculation> taxCalculations) {
		this.taxCountryId = taxCountryId;
		this.taxRegionId = taxRegionId;
		this.code = code;
		this.rate = rate;
		this.taxCalculations = taxCalculations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tax_calculation_rate_id", unique = true, nullable = false)
	public Integer getTaxCalculationRateId() {
		return this.taxCalculationRateId;
	}

	public void setTaxCalculationRateId(Integer taxCalculationRateId) {
		this.taxCalculationRateId = taxCalculationRateId;
	}

	@Column(name = "tax_country_id", nullable = false, length = 2)
	public String getTaxCountryId() {
		return this.taxCountryId;
	}

	public void setTaxCountryId(String taxCountryId) {
		this.taxCountryId = taxCountryId;
	}

	@Column(name = "tax_region_id", nullable = false)
	public int getTaxRegionId() {
		return this.taxRegionId;
	}

	public void setTaxRegionId(int taxRegionId) {
		this.taxRegionId = taxRegionId;
	}

	@Column(name = "code", nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "rate", nullable = false, precision = 12, scale = 4)
	public double getRate() {
		return this.rate;
	}

	public void setRate(double rate) {
		this.rate = rate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxCalculationRate")
	public Set<TaxCalculation> getTaxCalculations() {
		return this.taxCalculations;
	}

	public void setTaxCalculations(Set<TaxCalculation> taxCalculations) {
		this.taxCalculations = taxCalculations;
	}

}
