package com.example.entity;
// Generated Dec 19, 2015 11:20:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Wishlist generated by hbm2java
 */
@Entity
@Table(name = "wishlist", catalog = "lovefashion", uniqueConstraints = @UniqueConstraint(columnNames = "customer_id") )
public class Wishlist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer wishlistId;
	private CustomerEntity customerEntity;
	private Date updatedAt;
	private Date createdAt;
	private Set<WishlistItem> wishlistItems = new HashSet<WishlistItem>(0);

	public Wishlist() {
	}

	public Wishlist(CustomerEntity customerEntity) {
		this.customerEntity = customerEntity;
	}

	public Wishlist(CustomerEntity customerEntity, Date updatedAt, Date createdAt, Set<WishlistItem> wishlistItems) {
		this.customerEntity = customerEntity;
		this.updatedAt = updatedAt;
		this.createdAt = createdAt;
		this.wishlistItems = wishlistItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "wishlist_id", unique = true, nullable = false)
	public Integer getWishlistId() {
		return this.wishlistId;
	}

	public void setWishlistId(Integer wishlistId) {
		this.wishlistId = wishlistId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", unique = true, nullable = false)
	public CustomerEntity getCustomerEntity() {
		return this.customerEntity;
	}

	public void setCustomerEntity(CustomerEntity customerEntity) {
		this.customerEntity = customerEntity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wishlist")
	public Set<WishlistItem> getWishlistItems() {
		return this.wishlistItems;
	}

	public void setWishlistItems(Set<WishlistItem> wishlistItems) {
		this.wishlistItems = wishlistItems;
	}

}
